### ISSUE TITLE
Spring Cleaning - Any Updates Planned?  Please Fork (to Keep a Copy on Your Account)

### ISSUE THREAD

**Issue by geraldb** [sportlabs/major-league-soccer#1]
@cecomp64   First thanks for your contributions and effort. A friendly reminder - are you still interested in any updates? No rush, no pressure.
Just asking because I will move the (unmaintained) repo out of the sportdb org - if you want to keep a copy, please fork a copy of this repo so you can continue (if and whenever you desire). Cheers.

**Comment by geraldb** [comment]
@cecomp64  FYI: I've moved the repo it's now at the new sportlabs org.

**Comment by cecomp64** [comment]
Thanks for the update! I will fork a copy tonight. I don't have any updates
planned in the near future.

**Comment by geraldb** [comment]
Thanks for your contributions. You're always welcome. No rush. The repo will stay for now at the new sportlabs org.
